version: '3.6'

services:
  app:
    container_name: 'perro_service'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: on-failure
    depends_on:
      - db_service
    environment:
      - POSTGRES_DB=perro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db_service
  db_service:
    image: postgres
    environment:
      - POSTGRES_DB=perro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - perro-db-data:/var/lib/postgres/data
    restart: always
volumes:
  perro-db-data: